# Generated by Django 3.1.2 on 2020-10-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('transmission', models.SmallIntegerField(choices=[(1, 'механика'), (2, 'автомат'), (3, 'робот')], default=1)),
                ('color', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='static/images/cars')),
            ],
        ),
    ]
