# Generated by Django 3.1.2 on 2020-10-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[('механика', 1), ('автомат', 2), ('робот', 3)], default='механика'),
        ),
    ]
